Avoid a linker bug where symbols are not found. > /usr/bin/ld.bfd.real: out/Release/obj.target/net/libnet.so: undefined reference to symbol 'SSL_ForceHandshake' > out/Release/obj.target/net/third_party/nss/libcrssl.so: error adding symbols: DSO missing from command line